DROP TABLE ENGORG PURGE;
DROP TABLE ENGDISCIPLINE PURGE;
DROP TABLE ENGLOC PURGE;
DROP TABLE ENGTOPICAREAS PURGE;
DROP TABLE ENGRELATEDCOURSE PURGE;
DROP TABLE ENGCLASS PURGE;
DROP TABLE ENGAGEMENT PURGE;
DROP SEQUENCE ENGAGEMENT_Engagement_ID_seq;
DROP TABLE CONTACT_ORG PURGE;
DROP SEQUENCE CONTACT_ORG_Org_ID_seq;
DROP TABLE ORGANIZATION PURGE;
DROP SEQUENCE ORGANIZATION_ORG_ID_SEQ;
DROP TABLE LOCATION PURGE;
DROP SEQUENCE LOCATION_Location_ID_seq;
DROP TABLE CLASS PURGE;
DROP TABLE CONTACT_CSU PURGE;
DROP SEQUENCE CONTACT_CSU_ID_SEQ;
DROP TABLE STATE PURGE;
DROP TABLE ACAD_DISC PURGE;
DROP SEQUENCE ACAD_DISC_DISC_ID_seq;
DROP TABLE TOPIC_AREAS PURGE;
DROP SEQUENCE TOPIC_AREAS_Topic_ID_seq;
DROP TABLE RELATED_COURSES PURGE;
DROP SEQUENCE ENG_TYPEID_SEQ;
DROP TABLE VAL_ENG_TYPE;
DROP TABLE VAL_STU_LVL;
DROP TABLE VAL_TIMEFRAME;
DROP SEQUENCE TIMEFRAME_TIMEFR_ID_SEQ;


--============================--


CREATE SEQUENCE TIMEFRAME_TIMEFR_ID_SEQ;

CREATE TABLE VAL_TIMEFRAME (
                TIMEFR_ID NUMBER(4) NOT NULL,
                TIMEFR_DESC VARCHAR2(30) NOT NULL,
                CONSTRAINT VAL_TIMEFRAME_PK PRIMARY KEY (TIMEFR_ID)
);

CREATE TABLE VAL_STU_LVL (
                STU_LVL_CODE VARCHAR2(3) NOT NULL,
                STU_LVL_DESC VARCHAR2(30) NOT NULL,
                CONSTRAINT VAL_STU_LVL_PK PRIMARY KEY (STU_LVL_CODE)
);

CREATE SEQUENCE ENG_TYPEID_SEQ;

CREATE TABLE VAL_ENG_TYPE (
                TYPE_ID NUMBER(5) NOT NULL,
                TYPE_DESC VARCHAR2(200) NOT NULL,
                CONSTRAINT VAL_ENG_TYPE_PK PRIMARY KEY (TYPE_ID)
);

CREATE TABLE RELATED_COURSES (
                COURSE_SUBJ VARCHAR2(4) NOT NULL,
                Course_Num VARCHAR2(5) NOT NULL,
                Course_Title VARCHAR2(50),
                CONSTRAINT RELATED_COURSES_PK PRIMARY KEY (COURSE_SUBJ,Course_Num)
);

CREATE SEQUENCE TOPIC_AREAS_Topic_ID_seq START WITH 1;

CREATE TABLE TOPIC_AREAS (
                Topic_ID NUMBER(6) NOT NULL,
                Topic_Name VARCHAR2(50) NOT NULL,
                CONSTRAINT TOPIC_AREAS_PK PRIMARY KEY (Topic_ID)
);


CREATE SEQUENCE ACAD_DISC_DISC_ID_seq START WITH 1;

CREATE TABLE ACAD_DISC (
                Disc_ID NUMBER(6) NOT NULL,
                Disc_Name VARCHAR2(50) NOT NULL,
                Disc_Desc VARCHAR2(120) NULL,
                CONSTRAINT ACAD_DISC_PK PRIMARY KEY (Disc_ID)
);


CREATE TABLE STATE (
                State_code CHAR(2) NOT NULL,
                STATE_DESC VARCHAR2(40) NOT NULL,
                CONSTRAINT STATE_CODE_PK PRIMARY KEY (State_code)
);


CREATE SEQUENCE CONTACT_CSU_ID_SEQ START WITH 1;

CREATE TABLE CONTACT_CSU (
                Contact_CSU_ID NUMBER(6) NOT NULL,
                Contact_CSU_First_Name VARCHAR2(25) NOT NULL,
                Contact_CSU_Last_Name VARCHAR2(20) NOT NULL,
                Contact_CSU_Phone_Area_Code CHAR(3) NOT NULL,
                Contact_CSU_Phone_Numb CHAR(7) NOT NULL,
                Contact_CSU_Phone_Ext VARCHAR2(6) DEFAULT NULL,
                Contact_CSU_Email VARCHAR2(30) NOT NULL,
                CONSTRAINT CONTACT_CSU_ID PRIMARY KEY (Contact_CSU_ID)
);


CREATE TABLE CLASS (
                CLASS_CRN CHAR(5) NOT NULL,
                CLASS_TERM VARCHAR2(6) NOT NULL,
                CLASS_SUBJ VARCHAR2(4) NOT NULL,
                CLASS_NUMB VARCHAR2(5) NOT NULL,
                CLASS_STUDENT_COUNT NUMBER(3) NOT NULL,
                CLASS_TITLE VARCHAR2(50),
                CLASS_TEACHER_ID NUMBER(6) NOT NULL,
                CONSTRAINT CLAS_ID PRIMARY KEY (CLASS_CRN, CLASS_TERM)
);


CREATE SEQUENCE LOCATION_LOCATION_ID_SEQ;

CREATE TABLE LOCATION (
                Loc_ID NUMBER(6) NOT NULL,
                Loc_Name VARCHAR2(50),
                Loc_Address1 VARCHAR2(40),
                Loc_Address2 VARCHAR2(40) DEFAULT NULL,
                Loc_City VARCHAR2(30),
                Loc_State_code CHAR(2) NOT NULL,
                Loc_Zip CHAR(5),
                Loc_County VARCHAR2(20),
                CONSTRAINT LOCATION_PK PRIMARY KEY (Loc_ID)
);


CREATE SEQUENCE ORGANIZATION_ORG_ID_SEQ;

CREATE TABLE ORGANIZATION (
                Org_ID NUMBER(6) NOT NULL,
                Org_Name VARCHAR2(75) NOT NULL,
                Org_Address1 VARCHAR2(40),
                Org_Address2 VARCHAR2(40) DEFAULT NULL,
                Org_ZIP CHAR(5),
                Org_City VARCHAR2(30),
                Org_State VARCHAR2(2) DEFAULT NULL,
                Org_Website VARCHAR2(200),
                CONSTRAINT ORGANIZATION_PK PRIMARY KEY (Org_ID)
);

CREATE SEQUENCE CONTACT_ORG_Org_ID_seq;

CREATE TABLE CONTACT_ORG (
                Org_ID NUMBER(6) NOT NULL,
                Contact_Org_ID NUMBER(6) NOT NULL,
                Contact_Org_First_Name VARCHAR2(30) NOT NULL,
                Contact_Org_Last_Name VARCHAR2(30) NOT NULL,
                Contact_Org_Phone_Area_Code CHAR(3) NOT NULL,
                Contact_Org_Phone_Numb CHAR(7) NOT NULL,
                Contact_Org_Phone_Ext VARCHAR2(6) DEFAULT NULL,
                Contact_Org_Email VARCHAR2(30) NOT NULL,
                CONSTRAINT CONTACT_ORG_PK PRIMARY KEY (Org_ID, Contact_Org_ID)
);

CREATE SEQUENCE ENGAGEMENT_Engagement_ID_seq START WITH 1
INCREMENT BY 1;

CREATE TABLE ENGAGEMENT (
                Eng_ID NUMBER(6) NOT NULL,
                Eng_Name VARCHAR2(50) NOT NULL,
                ENG_TYPE NUMBER(5) NOT NULL,
                Eng_Desc VARCHAR2(2500) NOT NULL,
                Eng_Details VARCHAR2(2500),
                Eng_Website VARCHAR2(200) NOT NULL,
                Eng_Start_Date DATE NOT NULL,
                Eng_End_Date DATE NOT NULL,
                Eng_Contact_CSU_ID NUMBER(6) NOT NULL,
                Eng_Date_Updated DATE NOT NULL,
                Eng_Student_Level VARCHAR2(3) NOT NULL,
                Eng_TimeFrame NUMBER(4) NOT NULL,
                CONSTRAINT ENGAGEMENT_PK PRIMARY KEY (Eng_ID)
);

CREATE TABLE ENGCLASS (
                Eng_ID NUMBER(6) NOT NULL,
                CLASS_CRN CHAR(5) NOT NULL,
                CLASS_TERM VARCHAR2(6) NOT NULL,
                Assessment VARCHAR2(2500) NULL,
                Assessment_Date DATE NULL,
                Student_Participants NUMBER(3) NULL,
                CONSTRAINT ENGAGECLASS_PK PRIMARY KEY (Eng_ID, CLASS_CRN, CLASS_TERM)
);


CREATE TABLE ENGRELATEDCOURSE (
                Eng_ID NUMBER(6) NOT NULL,
                COURSE_SUBJ VARCHAR2(4) NOT NULL,
                Course_Num VARCHAR2(5) NOT NULL,
                CONSTRAINT ENGRELATEDCOURSE_PK PRIMARY KEY (Eng_ID, COURSE_SUBJ, Course_Num)
);


CREATE TABLE ENGTOPICAREAS (
                Eng_ID NUMBER(6) NOT NULL,
                Topic_ID NUMBER(6) NOT NULL,
                CONSTRAINT ENGTOPICAREAS_PK PRIMARY KEY (Eng_ID, Topic_ID)
);


CREATE TABLE ENGLOC (
                Eng_ID NUMBER(6) NOT NULL,
                Loc_ID NUMBER(6) NOT NULL,
                OnCampus CHAR(1) NOT NULL,
                Primary_Loc CHAR(1) NOT NULL,
                CONSTRAINT ENGLOC_PK PRIMARY KEY (Eng_ID, Loc_ID)
);


CREATE TABLE ENGDISCIPLINE (
                Eng_ID NUMBER(6) NOT NULL,
                Disc_ID NUMBER(6) NOT NULL,
                CONSTRAINT ENGDISCIPLINE_PK PRIMARY KEY (Eng_ID, Disc_ID)
);


CREATE TABLE ENGORG (
                Eng_ID NUMBER(6) NOT NULL,
                Org_ID NUMBER(6) NOT NULL,
                Principle_Org CHAR(1) NOT NULL,
                CONSTRAINT ENGORG_PK PRIMARY KEY (Eng_ID, Org_ID)
);


ALTER TABLE ENGRELATEDCOURSE ADD CONSTRAINT ENGRELCRS_RELATED_COURSES_FK
FOREIGN KEY (COURSE_SUBJ, Course_Num)
REFERENCES RELATED_COURSES (COURSE_SUBJ, Course_Num)
NOT DEFERRABLE;

ALTER TABLE ENGTOPICAREAS ADD CONSTRAINT ENGTOPICAREAS_TOPIC_AREAS_FK
FOREIGN KEY (Topic_ID)
REFERENCES TOPIC_AREAS (Topic_ID)
NOT DEFERRABLE;

ALTER TABLE ENGDISCIPLINE ADD CONSTRAINT ENGDISCIPLINE_ACAD_DISC_fk
FOREIGN KEY (Disc_ID)
REFERENCES ACAD_DISC (Disc_ID)
NOT DEFERRABLE;

ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_STATE_FK
FOREIGN KEY (Loc_State_code)
REFERENCES STATE (State_code)
NOT DEFERRABLE;

ALTER TABLE ENGAGEMENT ADD CONSTRAINT ENGAGEMENT_CONTACT_CSU_FK
FOREIGN KEY (Eng_Contact_CSU_ID)
REFERENCES CONTACT_CSU (Contact_CSU_ID)
NOT DEFERRABLE;

ALTER TABLE CLASS ADD CONSTRAINT CLASS_CONTACT_CSU_FK
FOREIGN KEY (CLASS_TEACHER_ID)
REFERENCES CONTACT_CSU (Contact_CSU_ID)
NOT DEFERRABLE;

ALTER TABLE ENGCLASS ADD CONSTRAINT ENGAGECLASS_CLASS_FK
FOREIGN KEY (CLASS_CRN, CLASS_TERM)
REFERENCES class (CLASS_CRN, CLASS_TERM)
NOT DEFERRABLE;

ALTER TABLE ENGLOC ADD CONSTRAINT ENGLOC_LOC_FK
FOREIGN KEY (Loc_ID)
REFERENCES LOCATION (Loc_ID)
NOT DEFERRABLE;

ALTER TABLE CONTACT_ORG ADD CONSTRAINT CONTACT_ORG_ORGANIZATION_FK
FOREIGN KEY (Org_ID)
REFERENCES ORGANIZATION (Org_ID)
NOT DEFERRABLE;

ALTER TABLE ENGORG ADD CONSTRAINT ENGORG_ORGANIZATION_FK
FOREIGN KEY (Org_ID)
REFERENCES ORGANIZATION (Org_ID)
NOT DEFERRABLE;

ALTER TABLE ENGORG ADD CONSTRAINT ENGORG_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGDISCIPLINE ADD CONSTRAINT ENGDISCIPLINE_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGLOC ADD CONSTRAINT ENGLOC_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGTOPICAREAS ADD CONSTRAINT ENGTOPICAREAS_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGRELATEDCOURSE ADD CONSTRAINT ENGRELATEDCOURSE_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGCLASS ADD CONSTRAINT ENGAGECLASS_ENGAGEMENT_FK
FOREIGN KEY (Eng_ID)
REFERENCES ENGAGEMENT (Eng_ID)
NOT DEFERRABLE;

ALTER TABLE ENGAGEMENT ADD CONSTRAINT VAL_ENG_TYPE_ENGAGEMENT_FK
FOREIGN KEY (ENG_TYPE)
REFERENCES VAL_ENG_TYPE (TYPE_ID)
NOT DEFERRABLE;

ALTER TABLE ENGAGEMENT ADD CONSTRAINT ENG_VAL_TIMEFRAME_FK
FOREIGN KEY (ENG_TIMEFRAME)
REFERENCES VAL_TIMEFRAME (TIMEFR_ID)
NOT DEFERRABLE;

ALTER TABLE ENGAGEMENT ADD CONSTRAINT VAL_STU_LVL_ENGAGEMENT_FK
FOREIGN KEY (ENG_STUDENT_LEVEL)
REFERENCES VAL_STU_LVL (STU_LVL_CODE)
NOT DEFERRABLE;

ALTER TABLE CONTACT_CSU ADD CONSTRAINT CONTACT_CSU_EMAIL_ck
CHECK (regexp_like(Contact_CSU_Email,'^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$','i'));

ALTER TABLE CONTACT_ORG ADD CONSTRAINT CONTACT_ORG_EMAIL_ck
CHECK (regexp_like(Contact_Org_Email,'^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$','i'));